### PR TITLE
Added control to register container as a service and can recover

### PR DESCRIPTION
**Pull request by alberto-leon-crespo**
# Issue 87

### CODE REVIEW

**Comment by zazoomauro** [comment]
@alberto-leon-crespo 
1. Check standards 
2. Can you add some test to prove container service will be accessible from the self-container?

**Comment by alberto-leon-crespo** [comment]
@zazoomauro I get and error but i dont see details about the problem. Can u help me?

**Comment by zazoomauro** [comment]
@alberto-leon-crespo sure. hope to have this ready today

**Comment by zazoomauro** [comment]
I created a new PR https://github.com/zazoomauro/node-dependency-injection/pull/89

**Pull request closed without merging**
